// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.296
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecAidGitHubSamples.Tutorials
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class TutorialWhatIfFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TutorialWhatIf.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tutorial What If", "In order to have good examples\r\nI want some feature files", ProgrammingLanguage.CSharp, new string[] {
                        "TutorialSteps"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Tutorial What If")))
            {
                SpecAidGitHubSamples.Tutorials.TutorialWhatIfFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("What If There Is No Spoon")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Tutorial What If")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("TutorialSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("TutorialNoSpoonSteps")]
        public virtual void WhatIfThereIsNoSpoon()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("What If There Is No Spoon", new string[] {
                        "TutorialNoSpoonSteps"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "First Name",
                        "Last Name"});
            table1.AddRow(new string[] {
                        "Fox",
                        "Smith"});
#line 9
 testRunner.Given("I have a Person", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "First Name",
                        "Last Name"});
            table2.AddRow(new string[] {
                        "Fox",
                        "Smith"});
#line 13
 testRunner.Then("There is a Person", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Making People With Spaces")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Tutorial What If")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("TutorialSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("TutorialGivenUseAnActionSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("TutorialStoresSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("TutorialSpacesForAllSteps")]
        public virtual void MakingPeopleWithSpaces()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Making People With Spaces", new string[] {
                        "TutorialGivenUseAnActionSteps",
                        "TutorialStoresSteps",
                        "TutorialSpacesForAllSteps"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Tag It",
                        "StoreId",
                        "Name"});
            table3.AddRow(new string[] {
                        "<<Red>>",
                        "42",
                        "Red\'s Brick and Landscaping"});
#line 21
 testRunner.Given("I have Stores", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Emp Id",
                        "First Name",
                        "Middle Name",
                        "Last Name",
                        "Store",
                        "YearsOfService"});
            table4.AddRow(new string[] {
                        "1",
                        "\"Fox\"",
                        "\"C\"",
                        "\"Smith   \"",
                        "<<Red>>",
                        "1"});
            table4.AddRow(new string[] {
                        "2",
                        "\"Jayne\"",
                        "",
                        "\"Cobb    \"",
                        "<<Red>>",
                        "0"});
#line 25
 testRunner.Given("I have People", ((string)(null)), table4, "Given ");
#line 30
 testRunner.When("I Build the Store Employee Report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "!Notes",
                        "LineNumber",
                        "Line"});
            table5.AddRow(new string[] {
                        "",
                        "0",
                        "\"Store                                   \""});
            table5.AddRow(new string[] {
                        "",
                        "1",
                        "\"  Employee              Years of Service\""});
            table5.AddRow(new string[] {
                        "",
                        "2",
                        "\"                                        \""});
            table5.AddRow(new string[] {
                        "",
                        "3",
                        "\"Red\'s Brick and Landscaping             \""});
            table5.AddRow(new string[] {
                        "",
                        "4",
                        "\"  Fox Smith                            1\""});
            table5.AddRow(new string[] {
                        "",
                        "5",
                        "\"  Jayne Cobb                           0\""});
#line 32
 testRunner.Then("The Store Employee Report Shows", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
